### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by EroareS** [droitlab/droit-elementor-addons-troubleshoot#2]
Hello, 

Everything works on my site before to update Droit Elementor Addons.
The following error appears:

There has been a critical error on this website.
Learn more about troubleshooting WordPress.

In php  log 

Stack trace:
#0 /home/lexischo/public_html/wp-content/plugins/droit-elementor-addons/includes/manager.php(23): DROIT_ELEMENTOR\Manager\Widgets->init()
#1 /home/lexischo/public_html/wp-content/plugins/droit-elementor-addons/core.php(54): DROIT_ELEMENTOR\Manager->load()
#2 /home/lexischo/public_html/wp-content/plugins/droit-elementor-addons/plugins.php(40): DROIT_ELEMENTOR\Dtdr_Core->load()
#3 /home/lexischo/public_html/wp-includes/class-wp-hook.php(292): {closure}('')
#4 /home/lexischo/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#5 /home/lexischo/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#6 /home/lexischo/public_html/wp-settings.php(423): do_action('plugins_loaded')
#7 /home/lexischo/public_html/wp-config.php(106): require_once('/home/lexischo/...')
#8 /home/lexischo/public_ in /home/lexischo/public_html/wp-content/plugins/droit-elementor-addons/includes/widgets.php on line 15

Could you help me?

**Comment by dev-hazi** [comment]
Thanks for contacting with us. Please remove this plugin then again install  and active.


Thanks,

**Comment by EroareS** [comment]
I deleted the oluggin, I have reinstalled, and I have the same error. Could you to suggest me another solution. Thank you.

**Comment by dev-hazi** [comment]
Hi,
Can you please email us at support@droitthemes.com with a screenshot of your issue.
 
Thanks.
